version: '3.8'

services:
  # Servicio para el frontend
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - CHOKIDAR_USEPOLLING=true  # Necesario para la detección de cambios en algunos entornos como Docker

  # Servicio para el backend
  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - database
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/insurance
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    networks:
      - app-network

  # Servicio para la base de datos PostgreSQL
  database:
    build:
      context: ./database
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: insurance
    networks:
      - app-network

# Red común para que los servicios se puedan comunicar entre sí
networks:
  app-network:
    driver: bridge
